---

- name: add zivtech gpg key
  apt_key:
    keyserver: pgp.mit.edu
    id: FC6025C6CB92E5AA60B4AB8F8E8904A002E048F5

- name: add zivtech apt repo
  apt_repository:
    repo: deb http://apt.zivtech.com stable main trusty
    state: present
  register: zivtechaptrepo

- name: add openjdk apt repo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: 'present'
  register: jdkaptrepo

- name: update apt
  apt:
    update_cache: yes

- name: install java
  apt:
    name: openjdk-8-jre
    state: present

- name: install solr
  apt:
    name: solr
    state: present

- name: add create-solr-instance script
  copy:
    src: create-solr-instance
    dest: /usr/local/bin/create-solr-instance
    owner: root
    group: root
    mode: 0755

- name: add remove-solr-instance script
  copy:
    src: remove-solr-instance
    dest: /usr/local/bin/remove-solr-instance
    owner: root
    group: root
    mode: 0755
