---

- name: install postgres packages
  apt: name={{ item }} state=present
  with_items:
    - 'postgresql'
    - 'postgresql-contrib'

- name: start postgres service
  shell: service potsgres start

- name: create base postgres db
  postgresql_db:
  name: acme

- name: add postgres.cnf file for root
  template: src=postgres.cnf.j2 dest=/root/.postgres.cnf owner=root mode=0600

- name: ensure mysql is stopped
  shell: service postgres stop
