---

# Add rvm apt repo.
- apt_repository:
    repo: ppa:rael-gc/rvm

- name: install rvm
  apt:
    name: rvm
    state: present

# Initialize rvm binary.
- name: initialize rvm
  command: source /usr/share/rvm/scripts/rvm

# Install latest stable ruby version.
- name: install ruby
  command: rvm install 2.5.1

- name: install compass
  apt:
    name: ruby-compass
    state: present

- name: install gem bundler
  gem:
    name: bundler
    state: latest
