---

- name: update apt
  apt: update_cache=yes

- name: install php dependencies
  apt: name={{ item }} state=present
  with_items:
    - 'php5'
    - 'php5-cli'
    - 'php5-common'
    - 'php5-curl'
    - 'php5-dev'
    - 'php5-gd'
    - 'php5-imagick'
    - 'php5-json'
    - 'php5-ldap'
    - 'php5-mcrypt'
    - 'php5-mysql'
    - 'php5-readline'
    - 'php5-redis'
    - 'php5-soap'
    - 'imagemagick'
    - 'libapache2-mod-php5'
    - 'php-pear'

- name: install redis
  apt:
    name: redis-server
    state: present

- name: install memcached
  apt:
    name: memcached
    state: present

- name: install libzip
  apt:
    name: libzip-dev
    state: present

- name: install php zip
  pear:
    name: pecl/zip
    state: present

- import_tasks: php-ini.yml
